"""AI Researcher Assistant.

A modular academic research harness with LLM adapters, memory/RAG, skills,
and orchestration loops.
"""

__version__ = "0.1.0"
__author__ = "AI Researcher Assistant Contributors"
__email__ = ""

from ai_researcher_assistant.core import (
    AgentConfig,
    AgentError,
    BaseAgent,
    ConfigurationError,
    Conversation,
    LLMConfig,
    LLMError,
    MemoryConfig,
    MemoryError,
    Message,
    MessageRole,
    SkillError,
    SkillsConfig,
    get_config,
    load_config_from_env,
    update_config,
)
from ai_researcher_assistant.harness import (
    ContextCompactor,
    ProtocolRequest,
    ProtocolStore,
    TaskBoard,
    TaskRecord,
    TeamMailbox,
    TeamMessage,
    WorktreeIndex,
)
from ai_researcher_assistant.llm import (
    AnthropicLLM,
    BaseLLM,
    LLMResponse,
    OllamaLLM,
    OpenAILLM,
    create_llm,
    get_llm,
)
from ai_researcher_assistant.memory import (
    AcademicRAG,
    BaseEmbedding,
    BaseMemory,
    HashEmbedding,
    InMemoryVectorMemory,
    LongTermMemory,
    MemoryItem,
    OpenAIEmbedding,
    ShortTermMemory,
)
from ai_researcher_assistant.orchestration import (
    ExecutionState,
    ExecutionStatus,
    ExecutionStep,
    LLMCompilerLoop,
    LoggingMiddleware,
    LoopConfig,
    LoopType,
    Middleware,
    MiddlewareManager,
    PlanAndExecuteLoop,
    ReActLoop,
    ResearcherAgent,
    SubagentResult,
    SubagentRunner,
    SubagentSpec,
    SubagentTask,
    TelemetryMiddleware,
    create_loop,
)
from ai_researcher_assistant.skills import (
    BaseSkill,
    SkillLoader,
    SkillManifest,
    SkillParameter,
    SkillRegistry,
    get_skill_registry,
)

__all__ = [
    "__version__",
    "__author__",
    "__email__",
    "AgentConfig",
    "LLMConfig",
    "MemoryConfig",
    "SkillsConfig",
    "get_config",
    "load_config_from_env",
    "update_config",
    "BaseAgent",
    "Message",
    "Conversation",
    "MessageRole",
    "AgentError",
    "LLMError",
    "SkillError",
    "MemoryError",
    "ConfigurationError",
    "BaseLLM",
    "LLMResponse",
    "OpenAILLM",
    "AnthropicLLM",
    "OllamaLLM",
    "create_llm",
    "get_llm",
    "TaskBoard",
    "TaskRecord",
    "TeamMailbox",
    "TeamMessage",
    "ProtocolStore",
    "ProtocolRequest",
    "WorktreeIndex",
    "ContextCompactor",
    "BaseMemory",
    "BaseEmbedding",
    "HashEmbedding",
    "InMemoryVectorMemory",
    "MemoryItem",
    "ShortTermMemory",
    "LongTermMemory",
    "OpenAIEmbedding",
    "AcademicRAG",
    "BaseSkill",
    "SkillManifest",
    "SkillParameter",
    "SkillRegistry",
    "get_skill_registry",
    "SkillLoader",
    "ResearcherAgent",
    "SubagentRunner",
    "SubagentSpec",
    "SubagentTask",
    "SubagentResult",
    "ReActLoop",
    "PlanAndExecuteLoop",
    "LLMCompilerLoop",
    "LoopType",
    "LoopConfig",
    "create_loop",
    "ExecutionState",
    "ExecutionStep",
    "ExecutionStatus",
    "Middleware",
    "MiddlewareManager",
    "LoggingMiddleware",
    "TelemetryMiddleware",
]
